# -*- coding: utf-8 -*-
"""sneha1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jKSteqHJWYZ1HuxJh7VM4llgw3sgPgEM
"""



"""Addition of two number

"""

a=20
b=30
c=a+b
print(c)